apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mh10445/new-k8s-auth:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 4000
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: MONGO_HOST
              value: auth-mongo-srv
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: auth
            - name: JWT_EXPIRES_IN
              value: '2d'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: jwtsecret