apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: mh10445/new-k8s-orders:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /
              port: 4000
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: '4000'
            - name: MONGO_HOST
              value: orders-mongo-srv
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DB
              value: orders
            - name: JWT_EXPIRES_IN
              value: '2d'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: jwtsecret
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_HOST
              value: nats-srv
            - name: NATS_PORT
              value: '4222'
            - name: EXPIRATION_DATE
              value: '900'